server:
  port: 8082

keycloak:
  enabled: true
  realm: pegasus
  auth-server-url: http://localhost:8081/auth/
  ssl-required: external
  resource: messenger-server
  credentials:
    secret: 8c52ccfb-4c15-4e4c-8e0b-a10f1cc978cd
  bearer-only: true
  cors: true
  use-resource-role-mappings: true
  verify-token-audience: true

spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8081/auth/realms/pegasus/protocol/openid-connect/token/introspect
          introspection-client-id: messenger-server
          introspection-client-secret: 8c52ccfb-4c15-4e4c-8e0b-a10f1cc978cd
#        jwt:
#          jwk-set-uri: http://localhost:8081/auth/realms/pegasus/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/pegasus_messenger
    driver-class-name: org.postgresql.Driver
    username: pegasus
    password: pegasus

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

    hibernate:
      ddl-auto: update
#      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: dev
