server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8081/auth/realms/pegasus/protocol/openid-connect/token/introspect
          introspection-client-id: messenger-server
          introspection-client-secret: 8c52ccfb-4c15-4e4c-8e0b-a10f1cc978cd
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

    hibernate:
      ddl-auto: update
#      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: dev

websocket:
  message-broker-prefix: /topic
  destination-prefix: /app
  registry-endpoint: /socket

logging:
  level:
    org:
      springframework:
        web: DEBUG
